# Generated by Django 3.2.4 on 2021-08-13 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('size', models.IntegerField(validators=[
                    django.core.validators.MinValueValidator(
                        2), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('picture_url', models.TextField(max_length=2000)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
    ]
