name: puzzle_maker CI
on: push

jobs:
  name: test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    with:
      python-version: ''
    - run: pip install -r requirements.txt
    - run: python manage.py migrate
    - run: python manage.py test