name: puzzle_maker CI
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3'
      - run: cd puzlle_maker && pip install -r requirements.txt
      - run: cd puzlle_maker && python manage.py migrate
      - run: cd puzlle_maker && python manage.py test
